# Generated by Django 5.1.4 on 2025-02-07 23:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_sequence', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('FOCUSED', 'Focused'), ('CASUAL', 'Casual')], default='CASUAL', max_length=20)),
                ('focus_target', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('focus_time', models.DurationField(default=datetime.timedelta(0))),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_users', to='api.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'joined_at'],
            },
        ),
    ]
